In [ ]:
import pandas as pd

In [ ]:
columns = ['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital',  'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 'hours_week', 'native_country','label']

In [ ]:
features = ['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital',  'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 'hours_week', 'native_country']

In [ ]:
path ="https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

In [ ]:
df_train = pd.read_csv(path, skipinitialspace=True, names = columns, index_col =  False)

In [ ]:
df_train.head()

,age,workclass,fnlwgt,education,education_num,marital,occupation,relationship,race,sex,capital_gain,capital_loss,hours_week,native_country,label
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
# List continuous features
cont_features = df_train._get_numeric_data()
print(cont_features)
print(cont_features.columns)
print(len(cont_features.columns))

        age    fnlwgt  education_num  capital_gain  capital_loss  hours_week
0      39.0   77516.0           13.0        2174.0           0.0        40.0
1      50.0   83311.0           13.0           0.0           0.0        13.0
2      38.0  215646.0            9.0           0.0           0.0        40.0
3      53.0  234721.0            7.0           0.0           0.0        40.0
4      28.0  338409.0           13.0           0.0           0.0        40.0
...     ...       ...            ...           ...           ...         ...
32556  27.0  257302.0           12.0           0.0           0.0        38.0
32557  40.0  154374.0            9.0           0.0           0.0        40.0
32558  58.0  151910.0            9.0           0.0           0.0        40.0
32559  22.0  201490.0            9.0           0.0           0.0        20.0
32560  52.0  287927.0            9.0       15024.0           0.0        40.0

[32561 rows x 6 columns]
Index(['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss',
       'hours_week'],
      dtype='object')
6

In [ ]:
# list the categorical features
cate_features = df_train.select_dtypes('object')
print(cate_features.columns)
print(len(cate_features.columns))

Index(['workclass', 'education', 'marital', 'occupation', 'relationship',
       'race', 'sex', 'native_country', 'label'],
      dtype='object')
9

In [ ]:
# converting cont features to float format
df_train[cont_features.columns] = df_train[cont_features.columns].astype("float64")

In [ ]:
print(df_train[cont_features.columns])

        age    fnlwgt  education_num  capital_gain  capital_loss  hours_week
0      39.0   77516.0           13.0        2174.0           0.0        40.0
1      50.0   83311.0           13.0           0.0           0.0        13.0
2      38.0  215646.0            9.0           0.0           0.0        40.0
3      53.0  234721.0            7.0           0.0           0.0        40.0
4      28.0  338409.0           13.0           0.0           0.0        40.0
...     ...       ...            ...           ...           ...         ...
32556  27.0  257302.0           12.0           0.0           0.0        38.0
32557  40.0  154374.0            9.0           0.0           0.0        40.0
32558  58.0  151910.0            9.0           0.0           0.0        40.0
32559  22.0  201490.0            9.0           0.0           0.0        20.0
32560  52.0  287927.0            9.0       15024.0           0.0        40.0

[32561 rows x 6 columns]

In [ ]:
# this give description only of cont features
df_train.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [ ]:
# for description of all featuers
df_train.describe(include = 'all')

,age,workclass,fnlwgt,education,education_num,marital,occupation,relationship,race,sex,capital_gain,capital_loss,hours_week,native_country,label
count,32561.000000,32561,3.256100e+04,32561,32561.000000,32561,32561,32561,32561,32561,32561.000000,32561.000000,32561.000000,32561,32561
unique,NaN,9,NaN,16,NaN,7,15,6,5,2,NaN,NaN,NaN,42,2
top,NaN,Private,NaN,HS-grad,NaN,Married-civ-spouse,Prof-specialty,Husband,White,Male,NaN,NaN,NaN,United-States,<=50K
freq,NaN,22696,NaN,10501,NaN,14976,4140,13193,27816,21790,NaN,NaN,NaN,29170,24720
mean,38.581647,NaN,1.897784e+05,NaN,10.080679,NaN,NaN,NaN,NaN,NaN,1077.648844,87.303830,40.437456,NaN,NaN
std,13.640433,NaN,1.055500e+05,NaN,2.572720,NaN,NaN,NaN,NaN,NaN,7385.292085,402.960219,12.347429,NaN,NaN
min,17.000000,NaN,1.228500e+04,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,NaN,NaN
25%,28.000000,NaN,1.178270e+05,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
50%,37.000000,NaN,1.783560e+05,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
75%,48.000000,NaN,2.370510e+05,NaN,12.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,45.000000,NaN,NaN
max,90.000000,NaN,1.484705e+06,NaN,16.000000,NaN,NaN,NaN,NaN,NaN,99999.000000,4356.000000,99.000000,NaN,NaN

In [ ]:
# get the column index of cat features
categoricals = []
for i in cate_features:
  pos = df_train.columns.get_loc(i)
  categoricals.append(pos)

print(categoricals)

[1, 3, 5, 6, 7, 8, 9, 13, 14]

In [ ]:
# get the column index of cont features
continous = []
for i in cont_features:
  pos = df_train.columns.get_loc(i)
  continous.append(pos)

print(continous)

[0, 2, 4, 10, 11, 12]

In [ ]:
# CONVERTING CATE FEATURES TO CONT VALUES USING ENCODERS
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
print(cate_features)

df_train['workclass'] = le.fit_transform(df_train['workclass'])
df_train['education'] = le.fit_transform(df_train['education'])
df_train['marital'] = le.fit_transform(df_train['marital'])
df_train['occupation'] = le.fit_transform(df_train['occupation'])
df_train['relationship'] = le.fit_transform(df_train['relationship'])
df_train['race'] = le.fit_transform(df_train['race'])
df_train['sex'] = le.fit_transform(df_train['sex'])
df_train['native_country'] = le.fit_transform(df_train['native_country'])

print(cate_features)

              workclass   education             marital         occupation  \
0             State-gov   Bachelors       Never-married       Adm-clerical
1      Self-emp-not-inc   Bachelors  Married-civ-spouse    Exec-managerial
2               Private     HS-grad            Divorced  Handlers-cleaners
3               Private        11th  Married-civ-spouse  Handlers-cleaners
4               Private   Bachelors  Married-civ-spouse     Prof-specialty
...                 ...         ...                 ...                ...
32556           Private  Assoc-acdm  Married-civ-spouse       Tech-support
32557           Private     HS-grad  Married-civ-spouse  Machine-op-inspct
32558           Private     HS-grad             Widowed       Adm-clerical
32559           Private     HS-grad       Never-married       Adm-clerical
32560      Self-emp-inc     HS-grad  Married-civ-spouse    Exec-managerial

        relationship   race     sex native_country  label
0      Not-in-family  White    Male  United-States  <=50K
1            Husband  White    Male  United-States  <=50K
2      Not-in-family  White    Male  United-States  <=50K
3            Husband  Black    Male  United-States  <=50K
4               Wife  Black  Female           Cuba  <=50K
...              ...    ...     ...            ...    ...
32556           Wife  White  Female  United-States  <=50K
32557        Husband  White    Male  United-States   >50K
32558      Unmarried  White  Female  United-States  <=50K
32559      Own-child  White    Male  United-States  <=50K
32560           Wife  White  Female  United-States   >50K

[32561 rows x 9 columns]
              workclass   education             marital         occupation  \
0             State-gov   Bachelors       Never-married       Adm-clerical
1      Self-emp-not-inc   Bachelors  Married-civ-spouse    Exec-managerial
2               Private     HS-grad            Divorced  Handlers-cleaners
3               Private        11th  Married-civ-spouse  Handlers-cleaners
4               Private   Bachelors  Married-civ-spouse     Prof-specialty
...                 ...         ...                 ...                ...
32556           Private  Assoc-acdm  Married-civ-spouse       Tech-support
32557           Private     HS-grad  Married-civ-spouse  Machine-op-inspct
32558           Private     HS-grad             Widowed       Adm-clerical
32559           Private     HS-grad       Never-married       Adm-clerical
32560      Self-emp-inc     HS-grad  Married-civ-spouse    Exec-managerial

        relationship   race     sex native_country  label
0      Not-in-family  White    Male  United-States  <=50K
1            Husband  White    Male  United-States  <=50K
2      Not-in-family  White    Male  United-States  <=50K
3            Husband  Black    Male  United-States  <=50K
4               Wife  Black  Female           Cuba  <=50K
...              ...    ...     ...            ...    ...
32556           Wife  White  Female  United-States  <=50K
32557        Husband  White    Male  United-States   >50K
32558      Unmarried  White  Female  United-States  <=50K
32559      Own-child  White    Male  United-States  <=50K
32560           Wife  White  Female  United-States   >50K

[32561 rows x 9 columns]

In [ ]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values = 0, strategy = 'mean')
imp.fit_transform(df_train[features])

array([[3.90000000e+01, 7.00000000e+00, 7.75160000e+04, ...,
        1.87142857e+03, 4.00000000e+01, 3.90000000e+01],
       [5.00000000e+01, 6.00000000e+00, 8.33110000e+04, ...,
        1.87142857e+03, 1.30000000e+01, 3.90000000e+01],
       [3.80000000e+01, 4.00000000e+00, 2.15646000e+05, ...,
        1.87142857e+03, 4.00000000e+01, 3.90000000e+01],
       ...,
       [5.80000000e+01, 4.00000000e+00, 1.51910000e+05, ...,
        1.87142857e+03, 4.00000000e+01, 3.90000000e+01],
       [2.20000000e+01, 4.00000000e+00, 2.01490000e+05, ...,
        1.87142857e+03, 2.00000000e+01, 3.90000000e+01],
       [5.20000000e+01, 5.00000000e+00, 2.87927000e+05, ...,
        1.87142857e+03, 4.00000000e+01, 3.90000000e+01]])

In [ ]:
df_train.head()

,age,workclass,fnlwgt,education,education_num,marital,occupation,relationship,race,sex,capital_gain,capital_loss,hours_week,native_country,label
0,39.0,7,77516.0,9,13.0,4,1,1,4,1,2174.0,0.0,40.0,39,<=50K
1,50.0,6,83311.0,9,13.0,2,4,0,4,1,0.0,0.0,13.0,39,<=50K
2,38.0,4,215646.0,11,9.0,0,6,1,4,1,0.0,0.0,40.0,39,<=50K
3,53.0,4,234721.0,1,7.0,2,6,0,2,1,0.0,0.0,40.0,39,<=50K
4,28.0,4,338409.0,9,13.0,2,10,5,2,0,0.0,0.0,40.0,5,<=50K

In [ ]:
# split the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_train[features], df_train['label'], random_state = 0)

In [ ]:
print(len(X_train))

24420

In [ ]:
# Naive Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
gnb = GaussianNB()
# train the model
pred  = gnb.fit(X_train, y_train).predict(X_test)

In [ ]:
print("Naive Bayes Accuracy: ", accuracy_score(y_test, pred, normalize = True))

Naive Bayes Accuracy:  0.7947426606068051